#ifndef UART_CONFIG_H
#define UART_CONFIG_H



/*Optins:	DATA_8BIT
			DATA_9BIT*/
#define 	UART1_WORD_LENGTH	DATA_8BIT
#define 	UART2_WORD_LENGTH	DATA_8BIT


/*Optins:	EVEN_PARITY
			ODD_PARITY
			NO_PARITY*/
#define 	UART1_PARITY_MODE	NO_PARITY
#define 	UART2_PARITY_MODE	NO_PARITY


/*Options:	ENABLE_RX		
			ENABLE_TX		
			ENABLE_BOTH*/
#define 	UART1_RX_TX_ENABLE	ENABLE_BOTH
#define 	UART2_RX_TX_ENABLE	ENABLE_BOTH

#endif
